version: '2'

services:
  postgres:
    image: postgres:latest
    volumes:
      - /srv/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=teamcity
      - POSTGRES_USER=teamcity
      - POSTGRES_DB=teamcity
    ports:
      - "5432:5432"

  teamcity:
    restart: on-failure
    image: jetbrains/teamcity-server:latest
    depends_on:
      - java
    volumes:
      - /srv/teamcity/data:/data/teamcity_server/datadir
      - /srv/teamcity/logs:/opt/teamcity/logs
    ports:
      - "8080:8111"

  teamcity_agent:
    restart: on-failure
    image: lunarfrog/teamcity-agent-dotnet:latest
    depends_on:
      - java
    links:
      - teamcity:teamcity
    volumes:
      - /srv/teamcity/agents/001/conf:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=teamcity:8111
      - AGENT_NAME="tcagent_docker"

  java:
    restart: on-failure
    image: openjdk:8u212-jdk

